import "bootstrap/dist/css/bootstrap.min.css";
import Header from "../components/Header/Header";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ko">
      <body>
        <Header />  
        {children}
      </body>
    </html>
  )
}
